### ISSUE TITLE
failed to connect to all address

### ISSUE THREAD

**Issue by zehuichen123** [karthiksharma98/sap-starterkit#2]
Hi, I am trying to use sap-starterkit offline. I followed the step by firstly running `source start_toolkit.sh` with the following output:
```
(yolo) xxxxxx\chenzehui@cn1514001928l:~/code/yolo/sap-starterkit$ source start_toolkit.sh 
loading annotations into memory...
Done (t=0.64s)
creating index...
index created!
Starting ImageService RPC Server. Listening on port 5007
Starting ResultService RPC Server. Listening on port 5008
Welcome to the sap_toolkit.   Type help or ? to list commands.

(server) 
```
However, when I run `start_det_baseline.sh`, I got the following error:
```
(yolo) xxxx\chenzehui@cn1514001928l:~/code/yolo/sap-starterkit$ source start_det_baseline.sh 
loading annotations into memory...
Done (t=0.68s)
creating index...
index created!
Loading model
The model and loaded state dict do not match exactly

unexpected key in source state_dict: roi_head.mask_head.convs.0.conv.weight, roi_head.mask_head.convs.0.conv.bias, roi_head.mask_head.convs.1.conv.weight, roi_head.mask_head.convs.1.conv.bias, roi_head.mask_head.convs.2.conv.weight, roi_head.mask_head.convs.2.conv.bias, roi_head.mask_head.convs.3.conv.weight, roi_head.mask_head.convs.3.conv.bias, roi_head.mask_head.upsample.weight, roi_head.mask_head.upsample.bias, roi_head.mask_head.conv_logits.weight, roi_head.mask_head.conv_logits.bias

Traceback (most recent call last):
  File "det_baseline_perf.py", line 155, in <module>
    detector_process()
  File "det_baseline_perf.py", line 58, in detector_process
    eval_client = EvalClient(config, verbose=True)
  File "/home/xxxxx/chenzehui/others/miniconda3/envs/yolo/lib/python3.8/site-packages/sap_toolkit/client.py", line 74, in __init__
    response = self.stub.GetShm(eval_server_pb2.Empty())
  File "/home/xxxxx/chenzehui/others/miniconda3/envs/yolo/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/xxxx/chenzehui/others/miniconda3/envs/yolo/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1619167480.157244467","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"created":"@1619167480.157240342","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
```
Did I miss anything?

**Comment by karthiksharma98** [comment]
Hi! Thanks for your interest in the challenge.

Did you run the second script while the first one is still running in another terminal? It seems like the second script is unable to connect to the benchmark toolkit server, which might happen if the server is not running.

**Comment by zehuichen123** [comment]
I've solved this problem by changing another computer hhhh thx !
